[build]
  # Force npm ci to install devDependencies and use npx with specific version
  command = "npm ci --include=dev && npx vite@5.4.19 build --config vite.config.production.ts"
  
  # Tell Netlify where to find the built frontend files
  publish = "dist/public"

[build.environment]
  # Set environment variables for build
  NODE_ENV = "development"
  NODE_VERSION = "20"

[[redirects]]
  # Handle client-side routing - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200