[build]
  # Use the bulletproof build script that we've tested successfully
  command = "npm ci && node build-netlify.js"
  
  # Tell Netlify where to find the built frontend files
  publish = "dist/public"

[build.environment]
  # Set environment variables for build
  NODE_ENV = "production"
  NODE_VERSION = "20"
  CI = "true"

[[redirects]]
  # Handle client-side routing - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets for better performance
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"