[build]
  # Force npm ci to install devDependencies and use npx with specific version
  command = "npm ci --include=dev && npx vite@5.4.19 build --config vite.config.production.ts"
  
  # Tell Netlify where to find the built frontend files
  publish = "dist/public"

[build.environment]
  # Set environment variables for build
  NODE_ENV = "production"
  NODE_VERSION = "20"

[build.processing]
  # EMERGENCY: Complete processing disable to prevent ALL compilation errors
  skip_processing = true

[build.processing.css]
  # Disable Netlify's CSS post-processing to prevent double-minification
  # Vite already handles CSS processing correctly
  bundle = false
  minify = false

[build.processing.js]
  # Disable Netlify's JS post-processing to prevent conflicts
  # Vite already handles JS bundling and minification
  bundle = false
  minify = false

[[redirects]]
  # Handle client-side routing - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200