[build]
  # Use the project's local vite installation, not npx which installs wrong version
  command = "npm ci && ./node_modules/.bin/vite build --config vite.config.production.ts"
  
  # Tell Netlify where to find the built frontend files
  publish = "dist/public"

[build.environment]
  # Set environment variables for build
  NODE_ENV = "production"
  NODE_VERSION = "20"

[[redirects]]
  # Handle client-side routing - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200