[build]
  # Use the installed vite version and simplified config
  command = "npm ci && ./node_modules/.bin/vite build --config vite.config.production.ts"
  
  # Tell Netlify where to find the built frontend files
  publish = "dist/public"

[build.environment]
  # Set environment variables for build
  NODE_ENV = "production"
  NODE_VERSION = "20"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[redirects]]
  # Handle client-side routing - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"