[build]
  # Use standard Vite build with the production config we tested
  command = "npm ci && npx vite build --config vite.config.production.ts"
  
  # Tell Netlify where to find the built frontend files
  publish = "dist/public"

[build.environment]
  # Set environment variables for build
  NODE_ENV = "production"
  NODE_VERSION = "20"

[[redirects]]
  # Handle client-side routing - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200